# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-07 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('content', models.TextField(default='', verbose_name='正文')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '联系我',
                'verbose_name_plural': '联系我',
            },
        ),
    ]
