# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-02 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('1', '草稿'), ('2', '发布'), ('3', '废弃')], max_length=1, verbose_name='状态'),
        ),
    ]
