# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-02 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180702_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_created'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=20, null=True, verbose_name='作者'),
        ),
    ]
